# Generated by Django 4.2.6 on 2023-10-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroRM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.IntegerField()),
                ('tipo_imovel', models.CharField(max_length=100)),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('cep', models.IntegerField()),
                ('valor_aluguel', models.IntegerField()),
                ('quantidade_quartos', models.IntegerField()),
                ('quantidade_banheiros', models.IntegerField()),
                ('descricao', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
