# Generated by Django 4.2.6 on 2023-10-10 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=255)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Curso', models.CharField(max_length=50)),
                ('Telefone', models.CharField(max_length=50)),
                ('Cpf', models.CharField(max_length=11)),
                ('Matricula', models.CharField(max_length=50)),
                ('Senha', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cadastrorm',
            options={'ordering': ['id'], 'verbose_name': 'Imovel', 'verbose_name_plural': 'Imoveis'},
        ),
    ]
