# Generated by Django 4.2.6 on 2023-10-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacoes',
            name='endereco',
            field=models.CharField(default='Endereço não fornecido', max_length=255),
        ),
    ]
