# Generated by Django 4.2.6 on 2023-10-10 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0002_usuarios_alter_cadastrorm_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CadastroRM',
            new_name='recomendacoes',
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'ordering': ['id'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
