# Generated by Django 4.2.7 on 2023-12-05 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0006_favorito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorito',
        ),
    ]
