# Generated by Django 4.2.7 on 2023-12-07 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts_app', '0009_delete_favorito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('recomendacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts_app.recomendacoes')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='recomendacoes',
            name='favoritos',
            field=models.ManyToManyField(related_name='favoritos', through='posts_app.Favorito', to=settings.AUTH_USER_MODEL),
        ),
    ]
