# Generated by Django 4.2.7 on 2024-02-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0010_favorito_recomendacoes_favoritos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recomendacoes',
            name='logradouro',
        ),
        migrations.AlterField(
            model_name='recomendacoes',
            name='cep',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='recomendacoes',
            name='cidade',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='recomendacoes',
            name='estado',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='recomendacoes',
            name='numero',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='recomendacoes',
            name='quantidade_banheiros',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='recomendacoes',
            name='quantidade_quartos',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='recomendacoes',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='recomendacoes',
            name='valor_aluguel',
            field=models.CharField(max_length=10),
        ),
    ]
